Fix reading of clock name
While trying to read a document with a clock, I get the following error:

    ...
    File ".../pytsdl/parser.py", line 1497, in _value_assign_clock
      clock.name = value[0].value
    TypeError: 'LiteralString' object does not support indexing

Removing the [0] seems to work.

Fixes #2